const ads = [
  {
    title: 'Skor dam 38',
    text: 'Lorem ipsum dolor sit amet...',
    price: '200 kr',
    location: 'Falköping',
    img: 'https://cdn.shopify.com/s/files/1/1479/3210/products/Linea_shoe_leather-Shoes-STB2045-220_TAN-1_600x.jpg?v=1659357475',
    category: 'shoes',
  },
  {
    title: 'Skor',
    text: 'Lorem ipsum dolor sit amet...',
    price: '500 kr',
    location: 'Falköping',
    img: 'https://images.squarespace-cdn.com/content/v1/61dcd32b3fb8bb4b5af9b560/1668707748473-KDWCBG5HOQ1XVF5E179L/Allbirds%2BShoes.png',
    category: 'shoes',
  },
  {
    title: 'Skor',
    text: 'Lorem ipsum dolor sit amet...',
    price: '300 kr',
    location: 'Falköping',
    img: 'https://cdn.thewirecutter.com/wp-content/media/2021/02/whitesneakers-2048px-4180.jpg?auto=webp&quality=75&width=1024',
    category: 'shoes',
  },
  {
    title: 'Hatt',
    text: 'Lorem ipsum dolor sit amet...',
    price: '100 kr',
    location: 'Göteborg',
    img: 'https://m.media-amazon.com/images/I/81rU14WgNZL._AC_SX342_.jpg',
    category: 'hats',
  },
  {
    title: 'Hammare',
    text: 'Lorem ipsum dolor sit amet...',
    price: '200 kr',
    location: 'Göteborg',
    img: 'https://m.media-amazon.com/images/I/41Mg9AGRbRL._AC_SY580_.jpg',
    category: 'tools',
  },
  {
    title: 'Skruvmejsel',
    text: 'Lorem ipsum dolor sit amet...',
    price: '200 kr',
    location: 'Göteborg',
    img: 'https://media.wickes.co.uk/image/upload/b_rgb:FFFFFF,c_pad,dpr_1.0,f_jpg,h_2250,q_auto:good,w_2250/c_pad,h_2250,w_2250/v1/products/wickes/T3274_143952_00?pgw=1&pgwact=1',
    category: 'tools',
  },
  {
    title: 'Hus',
    text: 'Lorem ipsum dolor sit amet...',
    price: '400 tkr',
    location: 'Göteborg',
    img: 'https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/download-23.jpg',
    category: 'housing',
  },
  {
    title: 'Bil',
    text: 'Lorem ipsum dolor sit amet...',
    price: '200 tkr',
    location: 'Göteborg',
    img: 'https://hogstavaxeln.se/wp-content/uploads/2022/04/2017_ferrari_laferrari-aperta_458A30E2-FEA1-4A82-8084-9910066FB492-30516-scaled.jpeg.jpg',
    category: 'vehicles',
  },
  {
    title: 'Moppe',
    text: 'Lorem ipsum dolor sit amet...',
    price: '20 tkr',
    location: 'Göteborg',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Red_Vespa_Scooter.jpg/1200px-Red_Vespa_Scooter.jpg',
    category: 'vehicles',
  },
];

export default ads;
