// const ads = [
//   {
//     title: 'Skor dam 38',
//     description: 'Lorem ipsum dolor sit amet...',
//     price: 200,
//     location: 'Norra Göteborg',
//     img: 'https://cdn.shopify.com/s/files/1/1479/3210/products/Linea_shoe_leather-Shoes-STB2045-220_TAN-1_600x.jpg?v=1659357475',
//     category: 'shoes',
//     isAvailable: true,
//     bookingRequests: ['Emil', 'Rosie123_cool', 'captain-america'],
//     author: 'millie',
//     startDate: '2022-11-28',
//     endDate: '2022-11-29',
//     // authorId: 'muW9vbM4tqfTSUu32meTjIngLPg1',
//     authorId: 'abcdefg',
//     id: '4d',
//     createdAt: '2022-12-02',
//   },
//   {
//     title: 'Skor',
//     description: 'Lorem ipsum dolor sit amet...',
//     price: 500,
//     location: 'Centrala Göteborg',
//     img: 'https://images.squarespace-cdn.com/content/v1/61dcd32b3fb8bb4b5af9b560/1668707748473-KDWCBG5HOQ1XVF5E179L/Allbirds%2BShoes.png',
//     category: 'shoes',
//     isAvailable: true,
//     bookingRequests: ['Millie'],
//     author: 'lindqvistsara',
//     startDate: '2022-11-30',
//     endDate: '2022-12-01',
//     authorId: 'muW9vbM4tqfTSUu32meTjIngLPg1',
//     id: '3c',
//     createdAt: '2022-12-02',
//   },
//   {
//     title: 'Skor',
//     description: 'Lorem ipsum dolor sit amet...',
//     price: 400,
//     location: 'Västra Göteborg',
//     img: 'https://cdn.thewirecutter.com/wp-content/media/2021/02/whitesneakers-2048px-4180.jpg?auto=webp&quality=75&width=1024',
//     category: 'shoes',
//     isAvailable: true,
//     bookingRequests: ['Edwin'],
//     startDate: '2022-11-30',
//     endDate: '2022-12-01',
//     author: 'lorem89',
//     authorId: 'muW9vbM4tqfTSUu32meTjIngLPg1',
//     id: '1a',
//     createdAt: '2022-12-02',
//   },
//   {
//     title: 'Hatt',
//     description: 'Lorem ipsum dolor sit amet...',
//     price: 100,
//     location: 'Centrala Göteborg',
//     img: 'https://m.media-amazon.com/images/I/81rU14WgNZL._AC_SX342_.jpg',
//     category: 'hats',
//     author: 'lindqvistsara',
//     isAvailable: false,
//     bookingRequests: [],
//     startDate: '2022-11-30',
//     endDate: '2022-12-01',
//     authorId: 'muW9vbM4tqfTSUu32meTjIngLPg1',
//     id: '2b',
//     createdAt: '2022-12-02',
//   },
//   // {
//   //   title: 'Hammare',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 200,
//   //   location: 'Göteborg',
//   //   img: 'https://m.media-amazon.com/images/I/41Mg9AGRbRL._AC_SY580_.jpg',
//   //   status: true,
//   //   author: 'lorem89',
//   // },
//   // {
//   //   title: 'Skruvmejsel',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 200,
//   //   location: 'Göteborg',
//   //   img: 'https://media.wickes.co.uk/image/upload/b_rgb:FFFFFF,c_pad,dpr_1.0,f_jpg,h_2250,q_auto:good,w_2250/c_pad,h_2250,w_2250/v1/products/wickes/T3274_143952_00?pgw=1&pgwact=1',
//   //   category: 'tools',
//   //   status: true,
//   //   author: 'lorem89',
//   // },
//   // {
//   //   title: 'Hus',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 400,
//   //   location: 'Göteborg',
//   //   img: 'https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/download-23.jpg',
//   //   category: 'housing',
//   //   status: true,
//   //   author: 'lorem89',
//   // },
//   // {
//   //   title: 'Bil',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 200,
//   //   location: 'Göteborg',
//   //   img: 'https://hogstavaxeln.se/wp-content/uploads/2022/04/2017_ferrari_laferrari-aperta_458A30E2-FEA1-4A82-8084-9910066FB492-30516-scaled.jpeg.jpg',
//   //   category: 'vehicles',
//   //   status: true,
//   //   author: 'lorem89',
//   // },
//   // {
//   //   title: 'Moppe',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 20,
//   //   location: 'Göteborg',
//   //   img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Red_Vespa_Scooter.jpg/1200px-Red_Vespa_Scooter.jpg',
//   //   category: 'vehicles',
//   //   status: true,
//   //   author: 'lindqvistsara',
//   // },
//   // {
//   //   title: 'Sandaler',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 1300,
//   //   location: 'Mora',
//   //   img: 'https://assets.hermes.com/is/image/hermesproduct/oran-sandal--202272Z%20JF-worn-1-0-0-800-800_b.jpg',
//   //   category: 'shoes',
//   //   status: true,
//   //   author: 'lindqvistsara',
//   // },
//   // {
//   //   title: 'Ducati Monster',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 1000,
//   //   location: 'Malmö',
//   //   img: 'https://www.fastbikes.se/images/stories/2019/2020/12-dec/MY21_DUCATI_MONSTER_PLUS_AMBIENCE__4__UC214574_High.jpg',
//   //   category: 'vehicles',
//   //   status: false,
//   //   author: 'lindqvistsara',
//   // },
//   // {
//   //   title: 'Hatt',
//   //   text: 'Lorem ipsum dolor sit amet...',
//   //   price: 100,
//   //   location: 'Karlstad',
//   //   img: 'https://images.fyndiq.se/images/f_auto/t_600x600/prod/e0b2e1d0a0024b15/4ee0324e6d79/svart-elegant-dam-hatt-mossa-svart',
//   //   category: 'hats',
//   //   status: true,
//   //   author: 'lindqvistsara',
//   // },
// ];

// export default ads;
