# This action for now is to clean/install all node dependencies and run format

name: prCheck CI
on:
  pull_request:
    branches: ['main']

jobs:
  prCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm start && npm run cypress:open
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
