# This action for now is to clean/install all node dependencies and run format

name: prCheck CI
on:
  pull_request:
    branches: ['main']

jobs:
  prCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm start
          run: npm run cypress:open
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
